test_cases = {
    "1": {
        "PID": {
            "family_name": "Pavarde",
            "given_name": "Vardas",
            "birth_date": "2008-07-10",
            "birth_place": "Lithuania, Vilnius",
            "nationality": ["LT"],
            "resident_address": "Žalgirio g. 112, Vilnius",
            "resident_country": "LT",
            "resident_state": "Vilniaus m. sav.",
            "resident_city": "Vilnius",
            "resident_postal_code": "LT-09300",
            "resident_street": "Žalgirio g.",
            "resident_house_number": "112",
            "personal_administrative_number": "30807100001",
            "portrait": "F",
            "family_name_birth": "Pavarde",
            "given_name_birth": "Vardas",
            "sex": 1,
            "email_address": "vardas69@pavarde.lt",
            "mobile_phone_number": "+3769999998",
            "document_number": "12345"
        }
    },
    "2": {
        "PID": {
            "family_name": "Simpsoniene",
            "given_name": "Marge",
            "birth_date": "1966-03-18",
            "birth_place": "Lithuania, Kaunas",
            "nationality": ["LT"],
            "resident_address": "Liepkalnio g. 97A, Vilnius",
            "resident_country": "LT",
            "resident_state": "Vilniaus m. sav.",
            "resident_city": "Vilnius",
            "resident_postal_code": "LT-09300",
            "resident_street": "Liepkalnio g.",
            "resident_house_number": "97A",
            "personal_administrative_number": "46603180001",
            "portrait": "F",
            "family_name_birth": "Bouvier",
            "given_name_birth": "Marge",
            "sex": 2,
            "email_address": "marge.simpsoniene@simpsonai.lt",
            "mobile_phone_number": "+3769999999",
            "document_number": "01234"
        }
    },
    "3": {
        "PID": {
            "family_name": "Pavarde",
            "given_name": "Vardas",
            "birth_date": "2008-07-10",
            "birth_place": "Lithuania, Vilnius",
            "nationality": ["LT"],
            "resident_address": "Žalgirio g. 112, Vilnius",
            "resident_country": "LT",
            "resident_state": "Vilniaus m. sav.",
            "resident_city": "Vilnius",
            "resident_postal_code": "LT-09300",
            "resident_street": "Žalgirio g.",
            "resident_house_number": "112",
            "personal_administrative_number": "30807100001",
            "portrait": "F",
            "family_name_birth": "Pavarde",
            "given_name_birth": "Vardas",
            "sex": 1,
            "email_address": "vardas69@pavarde.lt",
            "mobile_phone_number": "+3769999998",
            "issuance_date":"2024-10-15",
            "expiry_date":"2024-12-15",
            "document_number": "12345"
        }
    },
    "default": {
        "PID": {
            "family_name": "Simpsoniene",
            "given_name": "Marge",
            "birth_date": "1966-03-18",
            "birth_place": "Lithuania, Kaunas",
            "nationality": ["LT"],
            "resident_address": "Liepkalnio g. 97A, Vilnius",
            "resident_country": "LT",
            "resident_state": "Vilniaus m. sav.",
            "resident_city": "Vilnius",
            "resident_postal_code": "LT-09300",
            "resident_street": "Liepkalnio g.",
            "resident_house_number": "97A",
            "personal_administrative_number": "46603180001",
            "portrait": "F",
            "family_name_birth": "Bouvier",
            "given_name_birth": "Marge",
            "sex": 2,
            "email_address": "marge.simpsoniene@simpsonai.lt",
            "mobile_phone_number": "+3769999999",
            "issuance_date": "2024-10-15",
            "expiry_date": "2024-12-15",
            "document_number": "01234"
        }
    },
}
